### ISSUE TITLE
GPU Out of memory when deploying a server

### ISSUE THREAD

**Issue by tuong-olli** [kan-bayashi/ParallelWaveGAN#168]
I deploy a server ParallelWaveGAN in Google Cloud Server with GPU Tesla P4. 
Each time model synthesizes audio from mel spectrogram, GPU takes about 10 MiB until out of memory.
I used some method as:
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.benchmark = False
torch.cuda.set_device(0)
torch.cuda.empty_cache()
os.system(“sudo rm -rf ~/.nv”)" 
But It did not work fine.
Can you help me to solve this problem? Thanks very much.

**Comment by kan-bayashi** [comment]
Let me confirm some points:
- Did you use `with torch.no_grad()` block?
- Which PyTorch version did you use? Did you try with a different PyTorch version? In the case of CPU, PyTorch 1.4 or 1.5 seems to have the similar issue. https://github.com/kan-bayashi/ParallelWaveGAN/issues/160#issuecomment-639850145
- Did you call `torch.cuda.empty_cache()` after every inference?
- Could you check the memory usage with https://pytorch.org/docs/stable/cuda.html#torch.cuda.memory_allocated

**Comment by tuong-olli** [comment]
@kan-bayashi Thanks you. I fixed this issue by using PyTorch 1.0.1.
